(var __-p-s_-m-v_-r-e-g)

(i "./wiki.lisp" "handleWikiName")
(i "./search.lisp" "handleSearchQuery" "handleSearch")
(i "./quiz.lisp" "handleQuizIdResults" "handleQuizIdPlayIndex" "handleQuizIdPlay" "handleQuizIdEdit" "handleQuizCreate")
(i "./logout.lisp" "handleLogout")
(i "./login.lisp" "handleLogin")
(i "./root.lisp" "handle")
(i "./history.lisp" "handleWikiPageHistoryIdChanges" "handleWikiPageHistoryId" "handleWikiNameHistory")
(i "./edit.lisp" "handleWikiNameEdit")
(i "./create.lisp" "handleWikiNameCreate")
(i "./articles.lisp" "handleArticles")
(i "./show-tab.lisp" "showTab")

(lisp *UPDATE-STATE*)
