(var __-p-s_-m-v_-r-e-g)

(import "./wiki.lisp" "handleWikiName")
(import "./search.lisp" "handleSearchQuery" "handleSearch")
(import "./quiz.lisp" "handleQuizIdResults" "handleQuizIdPlayIndex" "handleQuizIdPlay" "handleQuizIdEdit" "handleQuizCreate")
(import "./logout.lisp" "handleLogout")
(import "./login.lisp" "handleLogin")
(import "./root.lisp" "handle")
(import "./history.lisp" "handleWikiPageHistoryIdChanges" "handleWikiPageHistoryId" "handleWikiNameHistory")
(import "./edit.lisp" "handleWikiNameEdit")
(import "./create.lisp" "handleWikiNameCreate")
(import "./articles.lisp" "handleArticles")
(import "./show-tab.lisp" "showTab")

(lisp *UPDATE-STATE*)
