image: devmohe/debian-roswell

# git clone http://192.168.2.150/root/wiki.git && cd wiki && git checkout state-machine

stages:
  - build-and-test

cache:
  paths:
    - cache-common-lisp
    - roswell-quicklisp-dists

before_script:
  - mkdir -p cache-common-lisp
  - mkdir -p roswell-quicklisp-dists
  - cp -ruT cache-common-lisp/ ~/.cache/common-lisp/
  - cp -ruT roswell-quicklisp-dists/ ~/.roswell/lisp/quicklisp/dists/
  - ln -sf $PWD/{spickipedia,lack,parenscript,clack,cl-coveralls} ~/.roswell/local-projects/

after_script:
  - cp -ruT ~/.cache/common-lisp/ cache-common-lisp/
  - cp -ruT ~/.roswell/lisp/quicklisp/dists/ roswell-quicklisp-dists/

build-and-test:
  stage: build-and-test
  script:
    - ros -s prove -e '(or (ignore-errors (prove:run :spickipedia-test)) (uiop:quit -1))'
    - ~/.roswell/bin/sblint

# ros -e "(ql:quickload '(:marshal :hunchentoot :clsql :cl-oauth :postmodern :rucksack :cl-fastcgi :toot :wookie :cl-redis :sqlite :fiveam :cl-js))"
