image: devmohe/debian-roswell

stages:
  - build
  - test

cache:
  paths:
    - cache
    - roswell

# git clone https://github.com/mohe2015/wiki && cd wiki && git checkout state-machine

before_script:
  - mkdir -p cache
  - mkdir -p roswell
  - cp -ruT cache/ ~/.cache/
  - cp -ruT roswell/ ~/.roswell/
  - ln -sf $PWD/{spickipedia,lack,parenscript,clack,cl-coveralls} ~/.roswell/local-projects/

after_script:
  - cp -ruT ~/.cache/ cache/
  - cp -ruT ~/.roswell/ roswell/

build:
  stage: build
  script:
    - ros -e "(ql:quickload '(:spickipedia :spickipedia-test))"

test:
  stage: test
  script:
    - ros --verbose -s prove -e '(or (ignore-errors (prove:run :spickipedia-test)) (uiop:quit -1))'

lint:
  stage: test
  script:
    - ros -e "(ql:quickload '(:marshal :hunchentoot :clsql :cl-oauth :postmodern :rucksack :cl-fastcgi :toot :wookie :cl-redis :sqlite :fiveam :cl-js))"
    - ~/.roswell/bin/sblint
