read -s -p "substitution-schedule password: " SUBSTITUTION_SCHEDULE_PASSWORD
RUST_BACKTRACE=1 SUBSTITUTION_SCHEDULE_USERNAME=schueler SUBSTITUTION_SCHEDULE_PASSWORD=$SUBSTITUTION_SCHEDULE_PASSWORD ros emacs
