version: 2
jobs:
  build:
    docker:
      - image: devmohe:debian-roswell

    steps:
      - checkout

      - run:
          name: Run tests
          command: $HOME/.roswell/bin/run-prove spickipedia/spickipedia-test.asd
