version: 2
jobs:
  build:
    docker:
      - image: devmohe/debian-roswell

    steps:
      - checkout

      - run:
          name: Initialize Submodules
          command: git submodule update --init

      - run:
          name: Make spickipedia loadable
          command: ln -s $PWD/{spickipedia,lack,parenscript,clack} ~/.roswell/local-projects/

      - run:
          name: Run tests
          command: COVERALLS=true ros -s prove -s cl-coveralls -e '(or (coveralls:with-coveralls (:exclude (list "t")) (prove:run :spickipedia-test)) (uiop:quit -1))'
